### ISSUE TITLE
upload daily wheels to the correct url

### ISSUE THREAD

**Issue by jreback** [MacPython/pandas-wheels#11]
@matthew-brett I believe I need to change our daily uploads to the correct url.

I suspect I need to set a secure env variable. can you elaborate?

**Comment by jreback** [comment]
https://github.com/MacPython/pandas-wheels/commit/5dfecec110ce3b71ee1fab10805eaae9f6f4bddb#commitcomment-21378765

**Comment by matthew-brett** [comment]
No, you should be good to go, just change the container name to `pre-release`.  The encrypted API key works for any of the Rackspace containers.

**Comment by jreback** [comment]
https://github.com/MacPython/pandas-wheels/blob/master/.travis.yml look ok?

**Comment by matthew-brett** [comment]
Yes, but I think you aren't using / don't need `UPLOAD_ARGS="--no-update-index";`.  That's also a bug in the numpy wheels travis.yml.

**Comment by jreback** [comment]
ahh ok, lmk take that out

**Comment by jreback** [comment]
@matthew-brett ok so I am using a daily branch now, and its hard coded to use pre-release, but this still points to: http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com

where is this defined?

**Comment by matthew-brett** [comment]
It's defined in the Rackspace interface - I have the password to the account, and I can make new containers, which Rackspace then allocates URLs, http and https.  The 'pre-release' container is at https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com

**Comment by jreback** [comment]
@matthew-brett still confused. Do I need to do anything then? pre-release is selected, but it seems to have an older definition AFAICT.

**Comment by matthew-brett** [comment]
You don't need to do anything other than set the container name in the last lines of the travis file (the wheel upload step).   Current master looks as if it's hard coded to the `wheels` container name, which would explain why you're uploading to there.

**Comment by jreback** [comment]
drat. didn't see that. fixed.

**Comment by jreback** [comment]
well we have some populating (others are failing to test out properly): http://8b8c47f30575e674b56d-47bd50c35cd79bd838daf386af554a83.r59.cf2.rackcdn.com/
