### ISSUE TITLE
Pandas 1.2.0 python 3.7 aarch64 wheels

### ISSUE THREAD

**Issue by janaknat** [MacPython/pandas-wheels#121]
The latest version of Pandas (1.2.0) doesn't have python 3.7 aarch64 wheels.
Logs from Travis shows 179 failures.

https://travis-ci.com/github/MacPython/pandas-wheels/jobs/464925073#L19716

Is this a known issue/being worked on?

**Comment by jreback** [comment]
we currently have very limited arm support because of travis ci issues - hopefully will be resolved at some point and release a wheel then

cc @simonjayhawkins

**Comment by simonjayhawkins** [comment]
yep that's the reason #37784 has not yet been closed, https://github.com/pandas-dev/pandas/issues/37784#issuecomment-751372454

MacPython is shared with other projects (and also the credits), so not really in a position to use that repo for troubleshooting.

we need to first be able to recreate the failures in the pandas repo. and ideally make the environments in MacPython and pandas more similar.

for conda-feedstock we use azure for the arm builds but it is much slower

**Comment by simonjayhawkins** [comment]
> for conda-feedstock we use azure for the arm builds but it is much slower

correction/clarification:

we use azure for the osx_arm64 which is not any slower

we also use azure for the linux_ppc64le which is much slower

we use drone for the linux_aarch64 which is slower but not as slow as the linux_ppc64le

**Comment by janaknat** [comment]
@simonjayhawkins Did you guys get credits from Travis?

**Comment by jreback** [comment]
nope
travis has totally ignored us
can u help?

**Comment by janaknat** [comment]
@jreback I've contacted Travis about the credits.

**Comment by janaknat** [comment]
@jreback Can you please check if you have the credits? Travis let me know that they've added some.

**Comment by jreback** [comment]
thanks @janaknat but nothing changed afaict

**Comment by janaknat** [comment]
@jreback So, the Travis folks have said they've provisioned the MacPython org with credits. Is there a separate dashboard for MacPython? Maybe it doesn't show up on the individual project dashboard?

**Comment by jreback** [comment]
ahh ok thanks. yeah we use that one but just for building (that's also shared across separate projects). our travis account is:https://travis-ci.com/github/pandas-dev/pandas

**Comment by janaknat** [comment]
Do I understand this correctly: pandas-wheels project is in MacPython org and uses Travis credits from there. The pandas-dev project uses your own Travis account and associated credits?

**Comment by jreback** [comment]
we had an account in travis-ci.org for pandas but not sure of the the new site

**Comment by janaknat** [comment]
@jreback Do you have enough Travis credits to debug the pandas python 3.7 issue?

**Comment by jreback** [comment]
we have 0 credits and have completely stopped using travis

**Comment by janaknat** [comment]
@jreback The latest pandas release has no aarch64 wheels. Was there any issues?

**Comment by jreback** [comment]
see above we r unable to test

**Comment by odidev** [comment]
@jreback @janaknat I have been working on resolving the 179 test failure for python v3.7 and it looks like that the reason for failures is the numpy version, the wheels for aarch64 in numpy were released from version **1.19.0** onwards.

I have modified the travis.yml for python v3.7 to use the numpy version as **1.19.1** instead of **1.16.5** and all the test failures have been resolved.

I will be happy to raise the pull request if you agree.

**Comment by jreback** [comment]
we are not going to change 1.2.x at all. for 1.3 we are using numpy 1.17.

**Comment by jreback** [comment]
this is really not a monitored repo, best to raise questions on the main pandas repo.

**Comment by janaknat** [comment]
@jreback Are the wheels created with a different repo?

**Comment by jreback** [comment]
wheels are created here but off the pandas main source

**Comment by janaknat** [comment]
@jreback Ok. Any feedback on https://github.com/MacPython/pandas-wheels/pull/132 ? That PR should fix python 3.8 and 3.9 failures for arm64.

**Comment by janaknat** [comment]
> @jreback @janaknat I have been working on resolving the 179 test failure for python v3.7 and it looks like that the reason for failures is the numpy version, the wheels for aarch64 in numpy were released from version **1.19.0** onwards.
> 
> I have modified the travis.yml for python v3.7 to use the numpy version as **1.19.1** instead of **1.16.5** and all the test failures have been resolved.
> 
> I will be happy to raise the pull request if you agree.

@jreback In this wheel build repo we are setting NP_BUILD_DEP=1.19.0 when building python 3.8 and python 3.9 aarch64 wheels. Is pandas 3.7 locked with numpy=1.16.5?

**Comment by jreback** [comment]
these will be updated for 1.3 T release time
