### ISSUE TITLE
osx wheels failing to build

### ISSUE THREAD

**Issue by jreback** [MacPython/pandas-wheels#20]
@matthew-brett any idea why the osx builds just started failing, e.g: https://travis-ci.org/MacPython/pandas-wheels/jobs/308739909

(2.7/3.5/3.6) all started a couple of days ago, working fine previously. looks like something may have changed in the environment? (e.g. it can't find pip).

**Comment by jreback** [comment]
cc @TomAugspurger @jorisvandenbossche

**Comment by matthew-brett** [comment]
Yes, the new default image has pip installed as pip2, and several other annoyances.  Try updating to the latest multibuild master?

**Comment by jreback** [comment]
updated, but getting this fail: https://travis-ci.org/MacPython/pandas-wheels/jobs/310948747

any idea?

**Comment by matthew-brett** [comment]
Oops - another xcode error message incompatibility.  Quick review for https://github.com/matthew-brett/delocate/pull/28 ?

**Comment by matthew-brett** [comment]
I uploaded a new version of delocate with the fix - try now?

**Comment by jreback** [comment]
is this a branch of multibuild?

**Comment by matthew-brett** [comment]
No, it's the delocate package, which is separate.  I updated that on pypi.

**Comment by jreback** [comment]
ok restarted my builds, but looks like it will be a while for travis to allocate. will ping: https://travis-ci.org/MacPython/pandas-wheels/builds/311074633

**Comment by jreback** [comment]
passed! thanks @matthew-brett
