### ISSUE TITLE
Python 2 builds breaking pybids

### ISSUE THREAD

**Issue by effigies** [MacPython/pandas-wheels#36]
Just to let you know, some time between Oct 10 and 17, the Python 2 nightly build started producing the following failure in pybids:

```
ImportError while importing test module '/home/travis/build/bids-standard/pybids/bids/analysis/tests/test_analysis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
bids/analysis/tests/test_analysis.py:2: in <module>
    from bids.analysis import Analysis
bids/__init__.py:4: in <module>
    from .analysis import Analysis
bids/analysis/__init__.py:1: in <module>
    from .analysis import Analysis
bids/analysis/analysis.py:2: in <module>
    from bids.layout import BIDSLayout
bids/layout/__init__.py:1: in <module>
    from .layout import BIDSLayout
bids/layout/layout.py:5: in <module>
    from .validation import BIDSValidator
bids/layout/validation.py:6: in <module>
    import pandas as pd
venv/lib/python2.7/site-packages/pandas/__init__.py:35: in <module>
    "the C extensions first.".format(module))
E   ImportError: C extension: No module named enum not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

As well as a number of similar errors. See, e.g., Travis builds [#792.4](https://travis-ci.org/bids-standard/pybids/jobs/442679130) or [#817.4](https://travis-ci.org/bids-standard/pybids/jobs/452188647).

This only occurs with `--pre` builds using the ManyLinux repository. Depending on the exact timing of the builds, it looks like it could have been caused by either of the last two commits: 131a2b7397c7acba7ac591e19484ef0f93f24ca9 or 93b492a50c44d56bd16aebffa3005ce497dd81d8

Related discussion: bids-standard/pybids#276

**Comment by effigies** [comment]
Sorry to pester, but does anybody have information on this? We're having to ignore errors in Python2+nightly altogether, in order to have a reliable indicator of other errors, which means upcoming changes in Pandas that only affect Python 2 are going to be completely missed until they're released.

**Comment by jreback** [comment]
have u seen: https://travis-ci.org/MacPython/pandas-wheels/builds

our nightly builds have been working for quite some time (small hiccup on 32 but for a little)

**Comment by effigies** [comment]
I'm not sure what to take away from that. We're still unable to use the package that is produced.

See, for example: https://travis-ci.org/bids-standard/pybids/jobs/465013222

**Comment by jreback** [comment]
you have a file named enum.py which is shadowing a built in module - not a great idea

**Comment by effigies** [comment]
Running `python -v -m bids.analysis`, I'm unable to see evidence of any `enum.py` except the builtin module, and searching through the file trees for pybids and our main dependencies, I can't see an `enum.py` anywhere. Sorry if I'm being dense...

**Comment by jreback** [comment]
then no idea

**Comment by effigies** [comment]
From playing around a bit more, it seems to be that Pandas uses `Enum`, but doesn't require `enum34` for Python versions <3.4. It looks like this dependency was introduced in pandas-dev/pandas#22802.

It wasn't erroring out in your tests, apparently, because `hypothesis` depends on it:

[`9103`](https://travis-ci.org/MacPython/pandas-wheels/jobs/464783556#L9103)` Collecting enum34; python_version == "2.7" (from hypothesis)`

Testing in bids-standard/pybids#315 to see if this clears up all of the errors.

**Comment by jreback** [comment]
hmm interesting can u make an issue on the main pandas repo

**Comment by effigies** [comment]
Was just about to submit a PR. Do you prefer to have an issue first?

**Comment by jreback** [comment]
what u did is fine thanks
