### ISSUE TITLE
Wheels for 3.8.0rc1

### ISSUE THREAD

**Issue by mattip** [MacPython/pandas-wheels#61]
multibuild and manylinux should now work with 3.8.0rc1, see MacPython/numpy-wheels#64 and MacPython/numpy-wheels#62. It is important to update multibuild to the HEAD of the latest `devel` branch.

I am not sure if pandas wants to try this now, 3.8 final is supposed to come out in a week or so.

**Comment by TomAugspurger** [comment]
I think @jbrockmendel is looking into this.

**Comment by TomAugspurger** [comment]
@jbrockmendel have you started on this? It seems like the 3.8 release is in progress: https://www.python.org/ftp/python/3.8.0/

I either misread, or the release date was changed, but https://www.python.org/dev/peps/pep-0569/#release-schedule has 10-14 (today) as the expected release date for 3.8

**Comment by jbrockmendel** [comment]
> have you started on this?

I think we've had a miscommunication.  I thought you were referring to https://github.com/pandas-dev/pandas/pull/28730.  I'm AFK for the next few hours, can look into this this afternoon if it is time-sensitive.

**Comment by TomAugspurger** [comment]
Gotcha. This is also needed so that we build 3.8 wheels.

I'll make a PR bumping multibuild so we can see what fails. Will probably
have you take over from there if that's OK though.
